using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraBars;

namespace Proposal
{
    public partial class Form1 : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void barButtonItem12_ItemClick(object sender, ItemClickEventArgs e)
        {
            Environment.Exit(0);
        }

        private void backstageViewButtonItem3_ItemClick(object sender, DevExpress.XtraBars.Ribbon.BackstageViewItemEventArgs e)
        {
            Environment.Exit(0);
        }

        private void backstageViewButtonItem1_ItemClick(object sender, DevExpress.XtraBars.Ribbon.BackstageViewItemEventArgs e)
        {
            ((Form)this.TopLevelControl).Dispose();
            new Alert(Alert.AlertType.SUCCESS, "Logout Success", null).Show();
            Proposal.Welcome FormThread = (Proposal.Welcome)Application.OpenForms["Welcome"];
                FormThread.Show();
        }

        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            Proposal.Welcome FormThread = (Proposal.Welcome)Application.OpenForms["Welcome"];
            if (FormThread != null)
                FormThread.Close();
        }

        private void barButtonItem11_ItemClick(object sender, ItemClickEventArgs e)
        {
            ((Form)this.TopLevelControl).Dispose();
            new Alert(Alert.AlertType.SUCCESS, "Logout Success", null).Show();
            Proposal.Welcome FormThread = (Proposal.Welcome)Application.OpenForms["Welcome"];
            FormThread.Show();
        }

        private void barButtonItem20_ItemClick(object sender, ItemClickEventArgs e)
        {
            this.defaultLookAndFeel1.LookAndFeel.SkinName = "Office 2016 Colorful";
        }

        private void barButtonItem21_ItemClick(object sender, ItemClickEventArgs e)
        {
            this.defaultLookAndFeel1.LookAndFeel.SkinName = "Office 2013";
        }

        private void barButtonItem22_ItemClick(object sender, ItemClickEventArgs e)
        {
            this.defaultLookAndFeel1.LookAndFeel.SkinName = "Visual Studio 2013 Dark";
        }
    }
}